'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, Heart, MessageCircle, Send, Users } from 'lucide-react';
import { toast } from 'sonner';
import { Field, FieldLabel } from '@/components/ui/field';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { addPost, commentOnPost, likePost, useDemo } from '@/lib/omnimarket/store';
import { marketById, markets } from '@/lib/omnimarket/markets';
import { type Post } from '@/lib/omnimarket/engine';
import { cn } from '@/lib/utils';
function PostCard({post}:{post:Post}) {
 const [expanded,setExpanded]=useState(false);const [comment,setComment]=useState('');const market=post.marketId?marketById(post.marketId):undefined;
 return <article className="panel p-5"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full border border-border bg-secondary font-mono text-sm text-muted-foreground">{post.initials}</span><div><h3 className="font-medium">{post.author}</h3><p className="text-sm text-muted-foreground">{post.author==='You'?'Your local post':'Sample community post'}</p></div></div><p className="mt-4 whitespace-pre-wrap break-words leading-relaxed">{post.text}</p>{market&&<Link href={`/market/${market.id}`} className="mt-4 flex items-center justify-between gap-3 rounded-lg border border-border bg-background px-3 py-3 text-sm text-muted-foreground hover:text-primary">{market.title}<ArrowUpRight className="size-4 shrink-0"/></Link>}<div className="mt-4 flex items-center gap-5 border-t border-border pt-3"><button aria-label={`Like post by ${post.author}`} aria-pressed={post.liked} className={cn('flex min-h-8 items-center gap-2 text-sm',post.liked?'text-destructive':'text-muted-foreground')} onClick={()=>likePost(post.id)}><Heart className="size-4" fill={post.liked?'currentColor':'none'}/>{post.likes}</button><button className="flex min-h-8 items-center gap-2 text-sm text-muted-foreground hover:text-foreground" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><MessageCircle className="size-4"/>{post.comments.length} {post.comments.length===1?'comment':'comments'}</button></div>{expanded&&<div className="mt-4 flex flex-col gap-3">{post.comments.map(c=><div className="rounded-lg bg-secondary px-3 py-3" key={c.id}><p className="text-sm font-medium">You · local comment</p><p className="mt-1 break-words text-sm leading-relaxed text-muted-foreground">{c.text}</p></div>)}<form className="flex items-end gap-2" onSubmit={e=>{e.preventDefault();try{commentOnPost(post.id,comment);setComment('');}catch(error){toast.error((error as Error).message);}}}><Field><FieldLabel htmlFor={`comment-${post.id}`}>Add a local comment</FieldLabel><Input id={`comment-${post.id}`} className="h-10" maxLength={300} value={comment} onChange={e=>setComment(e.target.value)} required onKeyDown={e=>{if(e.key==='Enter'&&(e.nativeEvent.isComposing||e.keyCode===229))e.preventDefault();}}/></Field><button aria-label="Send comment" className="action px-3" disabled={!comment.trim()}><Send className="size-4"/></button></form></div>}</article>;
}
export function CommunityFeed({marketId,compact=false}:{marketId?:string;compact?:boolean}) {
 const {state,ready}=useDemo();const [text,setText]=useState('');const [topic,setTopic]=useState(marketId??'');const posts=state.posts.filter(p=>!marketId||p.marketId===marketId);
 return <div className="flex flex-col gap-6">{!compact&&<div><p className="eyebrow">Many perspectives. One conversation.</p><h1 className="mt-2 text-3xl font-medium tracking-tight">The community</h1><p className="mt-2 text-muted-foreground">Share your thinking, not just your position.</p></div>}
 <div className={cn('grid items-start gap-6',!compact&&'xl:grid-cols-[minmax(0,1fr)_280px]')}><div className="flex min-w-0 flex-col gap-4">{compact&&<h2 className="section-title">Market discussion</h2>}<form className="panel flex flex-col gap-4 p-5" onSubmit={e=>{e.preventDefault();try{addPost(text,topic||undefined);setText('');toast.success('Your perspective was saved locally.');}catch(error){toast.error((error as Error).message);}}}><Field><FieldLabel htmlFor={`new-post-${marketId??'all'}`}>What&apos;s your perspective?</FieldLabel><Textarea id={`new-post-${marketId??'all'}`} value={text} onChange={e=>setText(e.target.value)} maxLength={600} placeholder="Share your thesis. What is the market missing?" className="min-h-24" required/></Field><div className="flex flex-wrap items-center justify-between gap-3">{!marketId&&<select className="field-input max-w-56" value={topic} onChange={e=>setTopic(e.target.value)} aria-label="Post topic"><option value="">General discussion</option>{markets.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select>}<span className="font-mono text-sm text-muted-foreground">{text.length}/600</span><button className="action" disabled={!ready||!text.trim()}><Send className="size-4"/>Post locally</button></div><p className="text-sm text-muted-foreground">Demo feed: your posts, likes and comments stay in this browser. Nothing is sent publicly.</p></form>{posts.length?posts.map(post=><PostCard key={post.id} post={post}/>):<div className="panel px-5 py-8 text-center text-muted-foreground">Be the first to share a local perspective on this market.</div>}</div>
 {!compact&&<aside className="panel flex flex-col gap-4 p-5"><Users className="size-6 text-primary"/><h2 className="text-lg font-medium">A better kind of debate.</h2><p className="leading-relaxed text-muted-foreground">Strong opinions, loosely held. Bring evidence, question assumptions, and respect the person on the other side.</p><div className="border-t border-border pt-4"><p className="text-sm font-medium">Keep in mind</p><ul className="mt-3 flex list-inside list-disc flex-col gap-2 text-sm leading-relaxed text-muted-foreground"><li>Discuss ideas, not individuals.</li><li>Check the resolution criteria.</li><li>Sample likes are illustrative.</li><li>No real users or public posting.</li></ul></div><Link href="/improvements" className="flex items-center gap-2 text-sm text-primary">Explore the design decisions <ArrowUpRight className="size-4"/></Link></aside>}
 </div></div>;
}
