'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Suspense, useState } from 'react';
import { ArrowDownUp, ArrowRight, ArrowUpRight, AudioLines, CirclePlay, Flame, Globe2, LayoutGrid, List, Search, SlidersHorizontal, Sparkles, TrendingUp, X } from 'lucide-react';
import { categories, compact, markets } from '@/lib/omnimarket/markets';
import { useDemo } from '@/lib/omnimarket/store';
import { cn } from '@/lib/utils';
import { MarketArt, MarketCard } from './market-card';
import { ProbabilityChart } from './probability-chart';
const Globe = dynamic(() => import('./globe'), { ssr: false, loading: () => <div className="flex h-full items-center justify-center text-primary/30"><Globe2 className="size-48" strokeWidth={.4}/></div> });
function Hero() { const feature = markets[0]; return <div className="grid gap-4 xl:grid-cols-[1.75fr_1fr]">
 <section className="panel relative isolate flex min-h-72 overflow-hidden sm:min-h-80"><div className="hero-grid pointer-events-none absolute inset-0"/><div className="relative z-10 flex w-full flex-col justify-center px-6 py-7 sm:w-[61%] sm:px-7"><div className="flex items-center gap-2 text-sm text-primary"><span className="size-1.5 rounded-full bg-primary"/>THE FUTURE IS AN OPEN MARKET</div><h1 className="mt-5 text-balance text-4xl leading-[1.13] font-medium tracking-[-.055em] sm:text-[43px]">Your perspective.<br/>Your edge.<br/><span className="text-primary">A world of possibilities.</span></h1><p className="mt-4 max-w-80 text-pretty leading-relaxed text-muted-foreground">Turn what you know into what comes next. Trade on the events shaping our world.</p><div className="mt-6 flex flex-wrap items-center gap-4"><a className="action" href="#market-grid">Explore markets <ArrowUpRight className="size-4"/></a><Link className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground" href="/improvements"><CirclePlay className="size-4"/>How it works</Link></div></div><div className="absolute top-0 right-0 hidden h-full w-[48%] sm:block"><Globe/><span className="pointer-events-none absolute right-6 bottom-5 flex items-center gap-2 font-mono text-sm text-muted-foreground"><span className="size-1.5 rounded-full bg-primary"/>DRAG TO EXPLORE</span></div></section>
 <section className="panel hidden flex-col p-5 xl:flex"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm text-primary"><Flame className="size-4"/>IN THE SPOTLIGHT</span><span className="rounded-md bg-secondary px-2 py-1 text-sm text-muted-foreground">Economics</span></div><Link href={`/market/${feature.id}`} className="mt-5 flex items-center gap-3"><MarketArt market={feature} className="size-12"/><h2 className="text-lg leading-snug font-medium tracking-tight">{feature.title}</h2></Link><div className="mt-5 flex items-end justify-between"><span className="font-mono text-4xl font-medium tracking-tight">78<span className="text-2xl">%</span><span className="ml-2 font-sans text-sm text-muted-foreground">chance</span></span><span className="flex items-center gap-1 font-mono text-sm text-primary"><TrendingUp className="size-4"/>8 pp this week</span></div><ProbabilityChart market={feature} compact/><div className="mt-auto grid grid-cols-2 gap-2"><Link className="outcome-yes" href={`/market/${feature.id}?outcome=Yes`}>Buy Yes <span>78¢</span></Link><Link className="outcome-no" href={`/market/${feature.id}?outcome=No`}>Buy No <span>22¢</span></Link></div><div className="mt-3 flex justify-between text-sm text-muted-foreground"><span>$2.45M sample volume</span><span>Closes Sep 30</span></div></section>
 </div>; }
function DiscoveryContent({ watchlist = false }: { watchlist?: boolean }) {
 const params = useSearchParams(); const { state } = useDemo();
 const [category, setCategory] = useState(params.get('category') ?? 'All markets'); const [query,setQuery] = useState(params.get('q') ?? ''); const [sort,setSort] = useState(params.get('sort') ?? 'trending'); const [layout,setLayout] = useState('grid');
 const filtered = markets.filter(m => (!watchlist || state.watchlist.includes(m.id)) && (category === 'All markets' || m.category === category) && `${m.title} ${m.category}`.toLowerCase().includes(query.toLowerCase().trim())).sort((a,b) => sort === 'volume' ? b.volume-a.volume : sort === 'closing' ? +new Date(a.close)-+new Date(b.close) : Math.abs(b.change)-Math.abs(a.change));
 const reset = () => { setCategory('All markets'); setQuery(''); setSort('trending'); };
 return <div className="flex flex-col gap-6">
 {!watchlist ? <><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold tracking-tight">A little foresight goes a long way.</h2><Sparkles className="hidden size-4 text-primary sm:block"/></div><p className="mt-1 text-sm text-muted-foreground">Big questions. Collective intelligence. Your next opportunity.</p></div><span className="hidden items-center gap-2 font-mono text-sm text-muted-foreground md:flex"><span className="size-1.5 rounded-full bg-primary"/>SANDBOX MODE</span></div><Hero/>
 <div className="flex flex-wrap items-center justify-between gap-4 border-y border-border py-4"><span className="flex items-center gap-2 text-sm font-medium"><AudioLines className="size-4 text-primary"/>Market pulse <span className="text-muted-foreground">/</span><span className="text-sm font-normal text-muted-foreground">Sample data</span></span><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm">{[markets[1],markets[0],markets[5]].map(m => <Link key={m.id} href={`/market/${m.id}`} className="flex items-center gap-2.5"><span className="text-muted-foreground">{m.category === 'Crypto' ? 'Bitcoin $120k' : m.category === 'Economics' ? 'Fed rate cut' : 'AI breakthrough'}</span><span className="font-mono">{m.price}%</span><span className={cn('font-mono',m.change > 0 ? 'text-primary' : 'text-destructive')}>{m.change > 0 ? '+' : ''}{m.change} pp</span></Link>)}</div></div></> : <div><p className="eyebrow">Your shortlist</p><h1 className="mt-2 text-3xl font-medium tracking-tight">Watchlist</h1><p className="mt-2 text-muted-foreground">Keep your next opportunity in sight. Saved only in this browser.</p></div>}
 <section id="market-grid" className="flex scroll-mt-6 flex-col gap-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><h2 className="section-title">{watchlist ? 'Saved markets' : 'Explore markets'}</h2><span className="rounded-md border border-border bg-card px-2 py-0.5 font-mono text-sm text-muted-foreground">{filtered.length}</span></div><div className="hidden items-center gap-1 rounded-lg border border-border p-1 sm:flex"><button aria-label="Grid view" aria-pressed={layout==='grid'} className={cn('icon-button size-7',layout==='grid' && 'bg-secondary text-foreground')} onClick={()=>setLayout('grid')}><LayoutGrid className="size-4"/></button><button aria-label="List view" aria-pressed={layout==='list'} className={cn('icon-button size-7',layout==='list' && 'bg-secondary text-foreground')} onClick={()=>setLayout('list')}><List className="size-4"/></button></div></div>
 <div className="flex flex-col justify-between gap-3 2xl:flex-row"><div className="scrollbar-none flex gap-1 overflow-x-auto" role="group" aria-label="Market category">{categories.map(c => <button key={c} className={cn('chip',category===c && 'chip-active')} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c==='All markets' && <Flame className="size-4"/>}{c}</button>)}</div><div className="flex items-center gap-2"><div className="flex min-h-9 flex-1 items-center gap-2 rounded-lg border border-border px-3 2xl:w-40"><Search className="size-4 shrink-0 text-muted-foreground"/><input className="min-w-0 w-full bg-transparent py-1.5 text-sm outline-none" aria-label="Search markets" placeholder="Search markets" value={query} onChange={e=>setQuery(e.target.value)}/>{query && <button aria-label="Clear search" onClick={()=>setQuery('')}><X className="size-3.5"/></button>}</div><div className="flex items-center gap-1 rounded-lg border border-border px-2"><ArrowDownUp className="size-3.5 text-muted-foreground"/><select aria-label="Sort markets" className="h-9 max-w-36 bg-background text-sm text-foreground outline-none" value={sort} onChange={e=>setSort(e.target.value)}><option value="trending">Trending</option><option value="volume">Top volume</option><option value="closing">Closing soon</option></select></div></div></div>
 {filtered.length ? <div className={cn('grid gap-4', layout==='grid' ? 'sm:grid-cols-2 xl:grid-cols-3' : 'sm:grid-cols-2')} >{filtered.map((market,i)=><MarketCard market={market} key={market.id} index={i}/>)}</div> : <div className="panel flex flex-col items-center gap-3 px-6 py-16 text-center"><Search className="size-8 text-muted-foreground"/><h3 className="text-lg font-medium">{watchlist && !state.watchlist.length ? 'Your next idea belongs here.' : 'No markets found'}</h3><p className="text-muted-foreground">{watchlist && !state.watchlist.length ? 'Tap the star on any market to add it to your watchlist.' : 'Try another search or reset your filters.'}</p>{watchlist && !state.watchlist.length ? <Link href="/" className="action-secondary">Explore markets <ArrowRight className="size-4"/></Link> : <button onClick={reset} className="action-secondary">Reset filters</button>}</div>}
 <div className="flex flex-wrap items-center justify-between gap-3 pt-1 text-sm text-muted-foreground"><span>Showing {filtered.length} of {watchlist ? state.watchlist.length : markets.length} sample markets</span><Link href="/improvements" className="flex items-center gap-1.5 hover:text-primary">Transparent by design <ArrowUpRight className="size-3.5"/></Link></div>
 </section>
 {!watchlist && <section className="panel flex flex-wrap items-center justify-between gap-5 px-6 py-5"><div className="flex items-center gap-4"><span className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Globe2 className="size-5"/></span><div><h3 className="font-medium">Good predictions start with a conversation.</h3><p className="mt-1 text-sm text-muted-foreground">Compare perspectives. Share your thesis. Find your edge.</p></div></div><Link href="/community" className="action-secondary">Explore community <ArrowUpRight className="size-4"/></Link></section>}
 </div>;
}
function SearchKey({ watchlist }: { watchlist: boolean }) { const params = useSearchParams(); return <DiscoveryContent key={params.toString()} watchlist={watchlist}/>; }
export function Discovery({ watchlist = false }: { watchlist?: boolean }) { return <Suspense fallback={<p className="text-muted-foreground">Loading markets…</p>}><SearchKey watchlist={watchlist}/></Suspense>; }
