'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Clock3, ExternalLink, ShieldCheck, Star, TrendingDown, TrendingUp, Users } from 'lucide-react';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { compact, type Market } from '@/lib/omnimarket/markets';
import { type Action, type Outcome } from '@/lib/omnimarket/engine';
import { toggleWatchlist, useDemo } from '@/lib/omnimarket/store';
import { cn } from '@/lib/utils';
import { MarketArt } from './market-card';
import { ProbabilityChart } from './probability-chart';
import { TradeTicket } from './trade-ticket';
import { CommunityFeed } from './community';
export function MarketDetail({ market, outcome, action }: { market: Market; outcome: Outcome; action: Action }) {
 const { state,ready } = useDemo(); const [range,setRange] = useState('1W'); const saved = state.watchlist.includes(market.id);
 return <div className="flex flex-col gap-6"><Link href="/" className="flex w-fit items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Back to markets</Link>
 <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="flex min-w-0 flex-col gap-6"><div className="flex items-start gap-4"><MarketArt market={market} className="size-16 sm:size-20"/><div className="flex-1"><div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><span>{market.category}</span><span>·</span><span className="text-primary">Sample market</span></div><h1 className="mt-2 text-balance text-2xl leading-tight font-medium tracking-tight sm:text-3xl">{market.title}</h1></div><button disabled={!ready} onClick={()=>toggleWatchlist(market.id)} className={cn('icon-button',saved&&'text-primary')} aria-label={saved?'Remove from watchlist':'Add to watchlist'} aria-pressed={saved}><Star className="size-5" fill={saved?'currentColor':'none'}/></button></div>
 <section className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="font-mono text-4xl font-medium">{market.price}%</span><span className="ml-2 text-muted-foreground">chance of Yes</span><p className={cn('mt-2 flex items-center gap-1.5 text-sm',market.change>=0?'text-primary':'text-destructive')}>{market.change>=0?<TrendingUp className="size-4"/>:<TrendingDown className="size-4"/>}{market.change>0?'+':''}{market.change} percentage points in sample week</p></div><ToggleGroup aria-label="Chart time range" value={[range]} onValueChange={values=>{if(values[0])setRange(values[0]);}} variant="outline">{['1D','1W','1M'].map(r=><ToggleGroupItem key={r} value={r}>{r}</ToggleGroupItem>)}</ToggleGroup></div><div className="mt-6"><ProbabilityChart market={market} range={range}/></div><p className="mt-3 text-sm text-muted-foreground">Illustrative price history, not a live feed. All ranges end at the current sample price.</p></section>
 <div className="grid grid-cols-2 gap-4 sm:grid-cols-3"><div className="panel p-4"><p className="text-sm text-muted-foreground">Sample volume</p><p className="mt-2 font-mono text-xl">${compact(market.volume)}</p></div><div className="panel p-4"><p className="flex items-center gap-1.5 text-sm text-muted-foreground"><Users className="size-3.5"/>Sample traders</p><p className="mt-2 font-mono text-xl">{market.traders.toLocaleString()}</p></div><div className="panel col-span-2 p-4 sm:col-span-1"><p className="flex items-center gap-1.5 text-sm text-muted-foreground"><Clock3 className="size-3.5"/>Closing date (UTC)</p><p className="mt-2 font-mono text-lg">{new Date(market.close).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'})}</p></div></div>
 <section className="panel p-5"><h2 className="flex items-center gap-2 text-lg font-medium"><ShieldCheck className="size-5 text-primary"/>Know what you&apos;re trading</h2><p className="mt-4 leading-relaxed text-muted-foreground">{market.rule}</p><a className="mt-4 flex w-fit items-center gap-2 text-sm text-primary" href={market.source} target="_blank" rel="noopener noreferrer">Reference source <ExternalLink className="size-3.5"/></a><p className="mt-4 border-t border-border pt-4 text-sm text-muted-foreground">Independent educational concept. Not affiliated with the reference source or the original OmniMarketX platform.</p></section>
 <CommunityFeed marketId={market.id} compact/>
 </div><div className="flex flex-col gap-4 xl:sticky xl:top-6"><TradeTicket key={`${market.id}-${outcome}-${action}`} market={market} initialOutcome={outcome} initialAction={action}/><Link href="/wallet" className="flex items-center justify-between rounded-lg border border-border px-4 py-3 text-sm text-muted-foreground hover:text-primary">Every trade has a paper trail.<ArrowUpRight className="size-4"/></Link></div></div></div>;
}
