'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, ChartNoAxesCombined, ReceiptText, Wallet } from 'lucide-react';
import { useDemo } from '@/lib/omnimarket/store';
import { marketById, money } from '@/lib/omnimarket/markets';
import { type Receipt } from '@/lib/omnimarket/engine';
import { cn } from '@/lib/utils';
import { MarketArt } from './market-card';
import { ReceiptDialog } from './receipt';
export function Portfolio() {
 const {state,ready}=useDemo(); const [receipt,setReceipt]=useState<Receipt|null>(null);
 const value=state.positions.reduce((total,p)=>{const m=marketById(p.marketId)!;return total+p.quantity*(p.outcome==='Yes'?m.price:100-m.price);},0);
 const cost=state.positions.reduce((total,p)=>total+p.cost,0); const pnl=value-cost;
 return <div className="flex flex-col gap-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">The bigger picture</p><h1 className="mt-2 text-3xl font-medium tracking-tight">Your portfolio</h1><p className="mt-2 text-muted-foreground">Every position, clearly in view. All values are virtual.</p></div><Link href="/" className="action">Explore markets <ArrowUpRight className="size-4"/></Link></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Total equity',amount:state.balance+value,foot:'Cash + current position value'},{label:'Available balance',amount:state.balance,foot:'Virtual USD, ready to trade'},{label:'Position value',amount:value,foot:`${state.positions.length} open ${state.positions.length===1?'position':'positions'}`},{label:'Unrealized P&L',amount:pnl,foot:'Includes buy fees; excludes sell fees'}].map((s,i)=><section key={s.label} className="panel p-5"><p className="text-sm text-muted-foreground">{s.label}</p><p className={cn('stat-value mt-3',i===3&&(pnl>=0?'text-primary':'text-destructive'))}>{money(s.amount)}</p><p className="mt-3 text-sm text-muted-foreground">{s.foot}</p></section>)}</div>
 <section className="flex flex-col gap-4"><div className="flex items-center justify-between"><h2 className="section-title">Open positions</h2><span className="text-sm text-muted-foreground">Marked to fixed sample prices</span></div>{!ready?<p className="text-muted-foreground">Loading your saved positions…</p>:state.positions.length ? <div className="flex flex-col gap-3">{state.positions.map(p=>{const m=marketById(p.marketId)!;const price=p.outcome==='Yes'?m.price:100-m.price;const positionPnl=p.quantity*price-p.cost;const closed=Date.now()>=+new Date(m.close);return <article key={`${p.marketId}-${p.outcome}`} className="panel flex flex-col gap-5 p-5"><div className="flex items-start gap-3"><MarketArt market={m} className="size-12"/><div className="flex-1"><Link href={`/market/${m.id}`} className="text-base font-medium hover:text-primary">{m.title}</Link><p className="mt-1 text-sm text-muted-foreground">{m.category} · <span className={p.outcome==='Yes'?'text-primary':'text-destructive'}>{p.outcome}</span> · {p.quantity.toLocaleString()} shares</p></div></div><div className="flex flex-wrap items-center justify-between gap-5 border-t border-border pt-4"><div className="flex flex-wrap gap-6"><div><p className="text-sm text-muted-foreground">Avg. entry incl. fees</p><p className="mt-1 font-mono">{(p.cost/p.quantity).toFixed(2)}¢</p></div><div><p className="text-sm text-muted-foreground">Current value</p><p className="mt-1 font-mono">{money(p.quantity*price)}</p></div><div><p className="text-sm text-muted-foreground">Unrealized P&L</p><p className={cn('mt-1 font-mono',positionPnl>=0?'text-primary':'text-destructive')}>{money(positionPnl)}</p></div></div><div className="flex gap-2"><Link href={`/market/${m.id}?outcome=${p.outcome}`} className="action-secondary">Buy more</Link>{closed?<span className="action-secondary opacity-50">Market closed</span>:<Link className="action" href={`/market/${m.id}?action=Sell&outcome=${p.outcome}`}>Sell {p.outcome} <ArrowUpRight className="size-4"/></Link>}</div></div></article>;})}</div>:<div className="panel flex flex-col items-center gap-4 px-6 py-16 text-center"><ChartNoAxesCombined className="size-9 text-primary"/><h3 className="text-xl font-medium">Your first position starts with a perspective.</h3><p className="max-w-md leading-relaxed text-muted-foreground">Explore a market, choose an outcome, and make a virtual trade. You have $10,000 to practice with.</p><Link href="/" className="action">Find your first market <ArrowRight className="size-4"/></Link></div>}</section>
 <section className="panel"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="text-lg font-medium">Recent activity</h2><Link className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-primary" href="/wallet">View all <ArrowUpRight className="size-4"/></Link></div>{state.receipts.length?state.receipts.slice(0,5).map(r=><button key={r.id} className="flex w-full items-center gap-3 border-b border-border px-5 py-4 text-left last:border-0 hover:bg-secondary" onClick={()=>setReceipt(r)}><ReceiptText className="size-5 shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{r.action==='Buy'?'Bought':'Sold'} {r.quantity} {r.outcome} shares</span><span className="block truncate text-sm text-muted-foreground">{r.title}</span></span><span className="font-mono text-sm">{r.action==='Buy'?'−':'+'}{money(r.net)}</span><ArrowUpRight className="size-4 shrink-0 text-muted-foreground"/></button>):<p className="px-5 py-8 text-sm text-muted-foreground">Completed trades and their receipts will appear here.</p>}</section><ReceiptDialog receipt={receipt} onClose={()=>setReceipt(null)}/>
 </div>;
}
