'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, AudioLines, ChartNoAxesCombined, ChevronDown, ChevronRight, CircleHelp, Compass, FlaskConical, Globe2, LayoutGrid, Menu, MessageCircle, Search, ShieldCheck, Sparkles, Star, Wallet, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useDemo } from '@/lib/omnimarket/store';
import { money } from '@/lib/omnimarket/markets';
const links = [{ href: '/', label: 'Markets', icon: LayoutGrid }, { href: '/portfolio', label: 'Portfolio', icon: ChartNoAxesCombined }, { href: '/watchlist', label: 'Watchlist', icon: Star }, { href: '/wallet', label: 'Wallet', icon: Wallet }, { href: '/community', label: 'Community', icon: MessageCircle }];
export function Shell({ children }: { children: React.ReactNode }) {
 const pathname = usePathname(); const router = useRouter(); const { state, storageWarning } = useDemo();
 const [mobile, setMobile] = useState(false); const [search, setSearch] = useState('');
 const active = pathname === '/home' || pathname.startsWith('/market/') ? '/' : pathname;
 const title = links.find(l => l.href === active)?.label ?? 'Improvements';
 return <>
  <a href="#main-content" className="fixed top-2 left-2 z-50 -translate-y-20 rounded-lg bg-primary px-4 py-2 text-primary-foreground focus:translate-y-0">Skip to content</a>
  {mobile && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-background/80 backdrop-blur-sm lg:hidden" onClick={() => setMobile(false)} />}
  <aside className={cn('fixed inset-y-0 left-0 z-40 flex w-52 flex-col border-r border-border bg-background text-foreground transition-transform lg:translate-x-0', mobile ? 'translate-x-0' : '-translate-x-full')}>
   <div className="px-5 py-6"><Link href="/" onClick={() => setMobile(false)} className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><AudioLines className="size-5" strokeWidth={2.5}/></span><span className="text-lg font-semibold tracking-tight">omnimarket<span className="text-primary">x</span></span></Link></div>
   <div className="px-4 py-2"><button onClick={() => router.push('/improvements')} className="flex w-full items-center justify-between rounded-lg border border-border bg-card px-3 py-2.5 text-card-foreground"><span className="flex items-center gap-2"><span className="flex size-6 items-center justify-center rounded bg-secondary text-muted-foreground"><Compass className="size-4"/></span>Personal workspace</span><ChevronDown className="size-4 text-muted-foreground"/></button></div>
   <nav aria-label="Main navigation" className="flex flex-col gap-1 px-3 py-5">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setMobile(false)} aria-current={active === href ? 'page' : undefined} className={cn('flex items-center gap-3 rounded-lg px-3 py-3 font-medium transition-colors', active === href ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary hover:text-foreground')}><Icon className="size-[18px]"/>{label}{label === 'Watchlist' && state.watchlist.length > 0 && <span className="ml-auto font-mono text-sm">{state.watchlist.length}</span>}{label === 'Markets' && <span className="ml-auto size-1.5 rounded-full bg-primary"/>}</Link>)}</nav>
   <div className="border-t border-border px-6 py-5"><p className="eyebrow">Explore</p><div className="mt-4 flex flex-col gap-4">{[{ name: 'Trending now', icon: Sparkles, query: 'sort=trending' }, { name: 'Global events', icon: Globe2, query: 'category=Politics' }, { name: 'Closing soon', icon: AudioLines, query: 'sort=closing' }].map(({name, icon: Icon, query}) => <Link key={name} onClick={() => setMobile(false)} href={`/?${query}`} className="flex items-center gap-3 text-muted-foreground hover:text-foreground"><Icon className="size-4"/>{name}</Link>)}</div></div>
   <div className="mt-auto px-4 pb-4"><div className="rounded-xl border border-primary/15 bg-primary/5 p-4"><FlaskConical className="size-5 text-primary"/><p className="mt-3 font-medium">Real ideas. Virtual stakes.</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Explore freely with $10,000 in demo funds.</p><Link href="/improvements" onClick={() => setMobile(false)} className="mt-3 flex items-center gap-2 text-sm text-primary">About this demo <ArrowUpRight className="size-4"/></Link></div><Link href="/improvements" onClick={() => setMobile(false)} className="mt-5 flex items-center gap-3 px-2 text-muted-foreground hover:text-foreground"><CircleHelp className="size-4"/>What&apos;s improved<ArrowUpRight className="ml-auto size-4"/></Link></div>
   <Link href="/portfolio" onClick={() => setMobile(false)} className="flex items-center gap-3 border-t border-border px-5 py-4"><span className="flex size-8 items-center justify-center rounded-full border border-border bg-secondary font-mono text-sm">NQ</span><span><span className="block text-sm font-medium">Numan Qureshi</span><span className="text-sm text-muted-foreground">Demo workspace</span></span><ChevronRight className="ml-auto size-4 text-muted-foreground"/></Link>
  </aside>
  <div className="min-h-screen lg:ml-52">
   <header className="flex h-[76px] items-center justify-between border-b border-border bg-background px-4 sm:px-7">
    <div className="flex items-center gap-3"><button className="icon-button lg:hidden" onClick={() => setMobile(!mobile)} aria-label="Open navigation" aria-expanded={mobile}>{mobile ? <X className="size-5"/> : <Menu className="size-5"/>}</button><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><span>Workspace</span><ChevronRight className="size-3.5"/><span className="text-foreground">{title}</span></div><span className="flex items-center gap-1.5 rounded-md border border-primary/20 bg-primary/5 px-2 py-1 text-sm text-primary"><span className="size-1.5 rounded-full bg-primary"/>Demo</span></div>
    <div className="flex items-center gap-3 sm:gap-5"><form className="hidden items-center gap-2 text-muted-foreground xl:flex" onSubmit={e => { e.preventDefault(); router.push(`/?q=${encodeURIComponent(search)}`); }}><Search className="size-4"/><input aria-label="Search all markets" className="w-40 bg-transparent text-sm outline-none" placeholder="Search anything..." value={search} onChange={e => setSearch(e.target.value)}/><kbd className="rounded border border-border px-1.5 text-sm">↵</kbd></form><Link href="/wallet" className="flex items-center gap-2"><Wallet className="size-4 text-muted-foreground"/><span className="font-mono text-sm font-medium">{money(state.balance)}</span><span className="hidden text-sm text-muted-foreground md:inline">USD</span></Link><Link href="/portfolio" className="action min-h-9 px-3"><span className="hidden sm:inline">My portfolio</span><ArrowUpRight className="size-4"/></Link><span className="hidden size-8 items-center justify-center rounded-full border border-border bg-secondary font-mono text-sm sm:flex">NQ</span></div>
   </header>
   {storageWarning && <p role="status" className="border-b border-border bg-secondary px-6 py-3 text-foreground">Saved data could not be loaded or browser storage is unavailable. This session may not persist.</p>}
   <main id="main-content" className="mx-auto max-w-[1660px] px-4 py-6 sm:px-7 sm:py-7">{children}</main>
   <footer className="mx-4 flex flex-wrap items-center justify-between gap-3 border-t border-border py-5 text-sm text-muted-foreground sm:mx-7"><span className="flex items-center gap-2"><ShieldCheck className="size-4"/>Independent concept · Sample markets · Virtual funds only</span><Link className="flex items-center gap-2 hover:text-primary" href="/improvements">Designed by Numan Qureshi <ArrowRight className="size-3.5"/></Link></footer>
  </div>
 </>;
}
