'use client';
import { useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Download, ReceiptText, RotateCcw, Search, ShieldCheck, Wallet } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useDemo,resetDemo } from '@/lib/omnimarket/store';
import { money } from '@/lib/omnimarket/markets';
import { type Receipt } from '@/lib/omnimarket/engine';
import { cn } from '@/lib/utils';
import { downloadFile, ReceiptDialog } from './receipt';
export function WalletView() {
 const {state,ready}=useDemo();const [query,setQuery]=useState('');const [action,setAction]=useState('All');const [receipt,setReceipt]=useState<Receipt|null>(null);const [reset,setReset]=useState(false);
 const filtered=state.receipts.filter(r=>(action==='All'||r.action===action)&&`${r.title} ${r.outcome} ${r.id}`.toLowerCase().includes(query.toLowerCase().trim()));
 function exportCsv(){const header=['id','timestamp_utc','market','outcome','action','shares','price_cents','gross_cents','fee_cents','net_cents','balance_after_cents'];const rows=filtered.map(r=>[r.id,r.timestamp,r.title,r.outcome,r.action,r.quantity,r.price,r.gross,r.fee,r.net,r.balanceAfter]);const escape=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;downloadFile([header,...rows].map(row=>row.map(escape).join(',')).join('\r\n'),'omnimarketx-transactions.csv','text/csv;charset=utf-8');}
 return <div className="flex flex-col gap-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Nothing hidden</p><h1 className="mt-2 text-3xl font-medium tracking-tight">Your wallet</h1><p className="mt-2 text-muted-foreground">Clear transactions. Complete receipts. Every cent accounted for.</p></div><button className="action-secondary" onClick={()=>setReset(true)} disabled={!ready}><RotateCcw className="size-4"/>Reset demo</button></div>
 <div className="grid gap-4 sm:grid-cols-[1.2fr_1fr]"><section className="panel border-primary/20 p-6"><span className="flex items-center gap-2 text-sm text-muted-foreground"><Wallet className="size-4"/>Available virtual balance</span><p className="mt-4 font-mono text-4xl font-medium tracking-tight">{money(state.balance)} <span className="text-base text-muted-foreground">USD</span></p><p className="mt-4 text-sm text-muted-foreground">Started with $10,000.00 · No real deposits or withdrawals.</p></section><section className="panel flex flex-col justify-center gap-3 p-6"><h2 className="flex items-center gap-2 font-medium"><ShieldCheck className="size-5 text-primary"/>A receipt you can come back to.</h2><p className="leading-relaxed text-muted-foreground">Open any transaction to see the exact market, outcome, share price, fees and balance after execution.</p><p className="text-sm text-muted-foreground">{state.receipts.length} completed trades · {money(state.receipts.reduce((sum,r)=>sum+r.fee,0))} total fees</p></section></div>
 <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border p-5"><h2 className="text-lg font-medium">Transaction history</h2><button className="action-secondary" disabled={!filtered.length} onClick={exportCsv}><Download className="size-4"/>Export filtered CSV</button></div><div className="flex items-center gap-3 border-b border-border p-4"><div className="flex flex-1 items-center gap-2 rounded-lg border border-border px-3"><Search className="size-4 text-muted-foreground"/><input className="h-10 min-w-0 w-full bg-transparent outline-none" aria-label="Search transaction history" placeholder="Search market, outcome or transaction ID" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="field-input w-auto" aria-label="Transaction type" value={action} onChange={e=>setAction(e.target.value)}><option value="All">All trades</option><option value="Buy">Buys</option><option value="Sell">Sells</option></select></div>
 {!ready?<p className="p-6 text-muted-foreground">Loading saved transactions…</p>:filtered.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Virtual trade history. Amounts include the 1% demo fee.</caption><thead className="bg-secondary/30 text-muted-foreground"><tr>{['Market / outcome','Action','Shares','Fee','Net amount','Receipt'].map(h=><th key={h} className="whitespace-nowrap px-4 py-3 font-normal">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t border-border"><td className="min-w-52 max-w-80 px-4 py-4"><p className="font-medium">{r.title}</p><p className="mt-1 text-muted-foreground">{r.outcome} · {new Date(r.timestamp).toLocaleDateString('en-US')} · {r.price}¢ / share</p></td><td className="px-4 py-4"><span className="flex items-center gap-1.5">{r.action==='Buy'?<ArrowUpRight className="size-4 text-muted-foreground"/>:<ArrowDownLeft className="size-4 text-primary"/>}{r.action}</span></td><td className="px-4 py-4 font-mono">{r.quantity}</td><td className="px-4 py-4 font-mono">{money(r.fee)}</td><td className={cn('whitespace-nowrap px-4 py-4 font-mono',r.action==='Sell'&&'text-primary')}>{r.action==='Buy'?'−':'+'}{money(r.net)}</td><td className="px-4 py-4"><button className="action-secondary" aria-label={`View receipt for ${r.action} ${r.quantity} ${r.outcome} shares`} onClick={()=>setReceipt(r)}><ReceiptText className="size-4"/>View</button></td></tr>)}</tbody></table></div>:<div className="flex flex-col items-center gap-3 px-5 py-16 text-center"><ReceiptText className="size-8 text-muted-foreground"/><h3 className="text-lg font-medium">{state.receipts.length?'No matching transactions':'Your paper trail starts here.'}</h3><p className="text-muted-foreground">{state.receipts.length?'Try another search or trade type.':'Complete a virtual trade to see a fully detailed receipt.'}</p></div>}
 </section><p className="text-sm leading-relaxed text-muted-foreground">CSV monetary values are exported as integer cents to preserve exact accounting. This is browser-local demo data, not an authoritative financial statement.</p>
 <ReceiptDialog receipt={receipt} onClose={()=>setReceipt(null)}/><Dialog open={reset} onOpenChange={setReset}><DialogContent><DialogHeader><DialogTitle>Start fresh?</DialogTitle><DialogDescription>This deletes your local trades, positions, watchlist, posts and comments, and restores $10,000 in virtual funds. This cannot be undone.</DialogDescription></DialogHeader><button className="action-secondary" onClick={()=>setReset(false)}>Keep my progress</button><button className="action" onClick={()=>{resetDemo();setReset(false);}}>Reset everything</button></DialogContent></Dialog>
 </div>;
}
